module.exports.loadIpcEvents = (ipcMain, window) => {
    const AmbientModeEvent = require("./AmbientModeEvent")
    const AudioVideoClickedEvent = require("./AudioVideoClickedEvent")
    const ButtonClickedEvent = require("./ButtonClickedEvent")
    const CloseEvent = require("./CloseEvent")
    const MaximizeEvent = require("./MaximizeEvent")
    const MinimizeEvent = require("./MinimizeEvent")
    const NavigatePageBackEvent = require("./NavigatePageBackEvent")
    const PauseEvent = require("./PauseEvent")
    const PlayEvent = require("./PlayEvent")
    const RateLimitedEvent = require("./RateLimitedEvent")
    const RestoreEvent = require("./RestoreEvent")
    const SeekEvent = require("./SeekEvent")
    const SongInfoEvent = require("./SongInfoEvent")

    AmbientModeEvent.load(ipcMain, window)
    AudioVideoClickedEvent.load(ipcMain, window)
    ButtonClickedEvent.load(ipcMain, window)
    CloseEvent.load(ipcMain, window)
    MaximizeEvent.load(ipcMain, window)
    MinimizeEvent.load(ipcMain, window)
    NavigatePageBackEvent.load(ipcMain, window)
    PauseEvent.load(ipcMain, window)
    PlayEvent.load(ipcMain, window)
    RateLimitedEvent.load(ipcMain, window)
    RestoreEvent.load(ipcMain, window)
    SeekEvent.load(ipcMain, window)
    SongInfoEvent.load(ipcMain, window)
}